version: "3.9"

services:
  reverse-proxy:
    container_name: wall-color-reverse-proxy
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "2000:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/nginx.conf:ro
