version: "3.9"

services:
  postgres:
    build:
      context: ./postgresdb
      dockerfile: deployment/Containerfile.local
    image: wall-color-postgres-image
    container_name: wall-color-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdb/volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}
    tty: true
