FROM docker.io/maven:3.9.12-eclipse-temurin-25-alpine 

# Set working directory
WORKDIR /app

# Expose the default Spring Boot port
EXPOSE 8080

# Start the app in dev mode (Spring Boot DevTools will auto-reload on changes)
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.fork=false"]
