version: "3.9"

services:
  backend:
    build:
      context: ./color-manager
      dockerfile: deployment/Containerfile.local
    image: wall-color-backend-image
    container_name: wall-color-backend
    ports:
      - "8080:8080"
    volumes:
      # Mount the local source code for hot reload
      - ./color-manager/src:/app/src:Z
      - ./color-manager/target:/app/target:Z
      - ./color-manager/pom.xml:/app/pom.xml:Z
      - ./color-manager/.mvn:/app/.mvn:Z
      - ./color-manager/mvnw:/app/mvnw:Z
    networks:
      - wall-color-net
    env_file:
      - color-manager/.env
    environment:
      - POSTGRES_PATH=postgre:5432
    depends_on:
      - postgre
    tty: true
