version: "3.9"

services:
  backend:
    build:
      context: ./color-manager
      dockerfile: deployment/Containerfile.local
    image: wall-color-backend-image:local
    container_name: wall-color-backend
    ports:
      - "8080:8080"
    volumes:
      # Mount the local source code for hot reload
      - ./color-manager/src:/app/src:Z
      - ./color-manager/target:/app/target:Z
      - ./color-manager/pom.xml:/app/pom.xml:Z
      - ./color-manager/.mvn:/app/.mvn:Z
      - ./color-manager/mvnw:/app/mvnw:Z
    environment:
      POSTGRES_PATH: postgres:5432
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      TOKEN_COOKIE_DOMAIN: ${TOKEN_COOKIE_DOMAIN:?TOKEN_COOKIE_DOMAIN is not set}
      TOKEN_MAX_AGE_SECONDS: ${TOKEN_MAX_AGE_SECONDS:?TOKEN_MAX_AGE_SECONDS is not set}
    depends_on:
      - postgres
    tty: true
