FROM macbre/nginx-http3:latest

USER root

# install CA tools
RUN apk add --no-cache ca-certificates

# copy your certificates
COPY ./deployment/certs/devCA.crt /usr/local/share/ca-certificates/devCA.crt

# update trust store
RUN update-ca-certificates

# switch back to original user if needed
USER nginx

CMD ["nginx", "-g", "daemon off;"]